-- =====================================================================================
-- File: 04_idx_fulfillment.sql
-- Description: Order and shipment tracking indexes for NewPOPSys database
-- Created: 2025-12-19
-- Package: 5 - Index Optimization
-- =====================================================================================
-- Purpose: Indexes for order management, shipment tracking, and fulfillment operations.
--          Supports PSP integration, order lifecycle tracking, and shipment status queries.
-- =====================================================================================

-- =============================================================================
-- STORE ORDERS QUERY INDEXES
-- =============================================================================

-- Store orders by campaign (already exists in brand_module_ddl.sql and psp_module_ddl.sql - SKIP)
-- CREATE INDEX idx_store_orders_campaign ON store_orders(campaign_id) WHERE deleted_at IS NULL;

-- Store orders by store (already exists - SKIP)
-- CREATE INDEX idx_store_orders_store ON store_orders(store_id) WHERE deleted_at IS NULL;

-- Store orders by assignment (already exists in psp_module_ddl.sql - SKIP)
-- CREATE INDEX idx_store_orders_assignment ON store_orders(store_assignment_id) WHERE deleted_at IS NULL;

-- Store orders by campaign and store (composite for finding store's orders in a campaign)
CREATE INDEX IF NOT EXISTS idx_store_orders_campaign_store
  ON store_orders(campaign_id, store_id)
  WHERE deleted_at IS NULL;

COMMENT ON INDEX idx_store_orders_campaign_store IS
  'Find all orders for a specific store in a specific campaign';

-- Store orders by campaign and status (for campaign order dashboards)
CREATE INDEX IF NOT EXISTS idx_store_orders_campaign_status
  ON store_orders(campaign_id, status, created_at DESC)
  WHERE deleted_at IS NULL;

COMMENT ON INDEX idx_store_orders_campaign_status IS
  'Find orders for a campaign filtered by status, sorted by creation time';

-- Store orders by PSP order reference (for PSP integration lookups)
CREATE INDEX IF NOT EXISTS idx_store_orders_psp_ref
  ON store_orders(psp_order_ref)
  WHERE psp_order_ref IS NOT NULL AND deleted_at IS NULL;

COMMENT ON INDEX idx_store_orders_psp_ref IS
  'Lookup orders by PSP-assigned reference number (for status callbacks)';

-- Store orders by order type (for distinguishing initial orders from reorders)
-- Already exists in psp_module_ddl.sql - SKIP
-- CREATE INDEX idx_store_orders_type ON store_orders(order_type) WHERE deleted_at IS NULL;

-- Store orders by batch label (for batch processing)
-- Already exists in psp_module_ddl.sql - SKIP
-- CREATE INDEX idx_store_orders_batch ON store_orders(batch_label) WHERE deleted_at IS NULL;

-- Store orders pending acknowledgment (partial index)
CREATE INDEX IF NOT EXISTS idx_store_orders_pending_ack
  ON store_orders(campaign_id, created_at)
  WHERE status = 'PENDING' AND deleted_at IS NULL;

COMMENT ON INDEX idx_store_orders_pending_ack IS
  'Find orders awaiting PSP acknowledgment';

-- Store orders acknowledged but not shipped (partial index)
CREATE INDEX IF NOT EXISTS idx_store_orders_acknowledged
  ON store_orders(campaign_id, acknowledged_at DESC)
  WHERE status = 'ACKNOWLEDGED' AND deleted_at IS NULL;

COMMENT ON INDEX idx_store_orders_acknowledged IS
  'Find acknowledged orders awaiting shipment';

-- Store orders by generation metadata
CREATE INDEX IF NOT EXISTS idx_store_orders_generated_by
  ON store_orders(generated_by_user_id, generated_at DESC)
  WHERE generated_by_user_id IS NOT NULL AND deleted_at IS NULL;

COMMENT ON INDEX idx_store_orders_generated_by IS
  'Find orders generated by a specific user or process';

-- Store orders cancelled (partial index for cancelled order tracking)
CREATE INDEX IF NOT EXISTS idx_store_orders_cancelled
  ON store_orders(cancelled_at DESC)
  WHERE cancelled_at IS NOT NULL AND deleted_at IS NULL;

COMMENT ON INDEX idx_store_orders_cancelled IS
  'Find cancelled orders, sorted by cancellation time';

-- =============================================================================
-- ORDER LINES QUERY INDEXES
-- =============================================================================

-- Order lines by store order (already exists in brand_module_ddl.sql and psp_module_ddl.sql - SKIP)
-- CREATE INDEX idx_order_lines_order ON order_lines(store_order_id) WHERE deleted_at IS NULL;

-- Order lines by kit item (already exists in psp_module_ddl.sql - SKIP)
-- CREATE INDEX idx_order_lines_kit_item ON order_lines(kit_item_id) WHERE deleted_at IS NULL;

-- Order lines by SKU (already exists in psp_module_ddl.sql - SKIP)
-- CREATE INDEX idx_order_lines_sku ON order_lines(sku) WHERE deleted_at IS NULL;

-- Order lines by order and kit item (composite for line item lookup)
CREATE INDEX IF NOT EXISTS idx_order_lines_order_kit_item
  ON order_lines(store_order_id, kit_item_id)
  WHERE deleted_at IS NULL;

COMMENT ON INDEX idx_order_lines_order_kit_item IS
  'Find specific line items in an order by kit item';

-- Order lines with quantity discrepancies (for quality monitoring)
CREATE INDEX IF NOT EXISTS idx_order_lines_qty_variance
  ON order_lines(store_order_id)
  WHERE (shipped_qty != ordered_qty OR delivered_qty != shipped_qty) AND deleted_at IS NULL;

COMMENT ON INDEX idx_order_lines_qty_variance IS
  'Find order lines with quantity discrepancies (shipped vs ordered, delivered vs shipped)';

-- =============================================================================
-- SHIPMENTS QUERY INDEXES
-- =============================================================================

-- Shipments by store order (already exists in brand_module_ddl.sql and psp_module_ddl.sql - SKIP)
-- CREATE INDEX idx_shipments_order ON shipments(store_order_id) WHERE deleted_at IS NULL;

-- Shipments by status (already exists - SKIP)
-- CREATE INDEX idx_shipments_status ON shipments(status) WHERE deleted_at IS NULL;

-- Shipments by carrier (already exists in psp_module_ddl.sql - SKIP)
-- CREATE INDEX idx_shipments_carrier ON shipments(carrier) WHERE deleted_at IS NULL;

-- Shipments in transit (partial index for active shipment tracking)
CREATE INDEX IF NOT EXISTS idx_shipments_in_transit
  ON shipments(shipped_at DESC)
  WHERE status = 'IN_TRANSIT' AND deleted_at IS NULL;

COMMENT ON INDEX idx_shipments_in_transit IS
  'Find all shipments currently in transit, sorted by ship date';

-- Shipments delivered (already exists in psp_module_ddl.sql - SKIP)
-- CREATE INDEX idx_shipments_delivered ON shipments(delivered_at DESC) WHERE deleted_at IS NULL;

-- Shipments with delivery exceptions (partial index)
CREATE INDEX IF NOT EXISTS idx_shipments_exceptions
  ON shipments(updated_at DESC)
  WHERE status = 'EXCEPTION' AND deleted_at IS NULL;

COMMENT ON INDEX idx_shipments_exceptions IS
  'Find shipments with delivery exceptions requiring attention';

-- Shipments by expected delivery window
CREATE INDEX IF NOT EXISTS idx_shipments_expected_delivery
  ON shipments(expected_delivery_date)
  WHERE expected_delivery_date IS NOT NULL AND deleted_at IS NULL;

COMMENT ON INDEX idx_shipments_expected_delivery IS
  'Find shipments by expected delivery date (for proactive monitoring)';

-- Shipments by tracking numbers GIN index (already exists in psp_module_ddl.sql - SKIP)
-- CREATE INDEX idx_shipments_tracking_numbers ON shipments USING GIN (tracking_numbers) WHERE deleted_at IS NULL;

-- Shipments with tracking updates
CREATE INDEX IF NOT EXISTS idx_shipments_last_tracked
  ON shipments(last_tracking_update_at DESC NULLS LAST)
  WHERE deleted_at IS NULL;

COMMENT ON INDEX idx_shipments_last_tracked IS
  'Find shipments by last tracking update time (for stale tracking detection)';

-- =============================================================================
-- SHIPMENT LINES QUERY INDEXES
-- =============================================================================

-- Shipment lines by shipment (already exists in brand_module_ddl.sql and psp_module_ddl.sql - SKIP)
-- CREATE INDEX idx_shipment_lines_shipment ON shipment_lines(shipment_id) WHERE deleted_at IS NULL;

-- Shipment lines by kit item (already exists in psp_module_ddl.sql - SKIP)
-- CREATE INDEX idx_shipment_lines_kit_item ON shipment_lines(kit_item_id) WHERE deleted_at IS NULL;

-- Shipment lines by shipment and kit item (composite)
CREATE INDEX IF NOT EXISTS idx_shipment_lines_shipment_kit_item
  ON shipment_lines(shipment_id, kit_item_id)
  WHERE deleted_at IS NULL;

COMMENT ON INDEX idx_shipment_lines_shipment_kit_item IS
  'Find specific items in a shipment by kit item';

-- =============================================================================
-- RECEIVE VERIFICATIONS QUERY INDEXES
-- =============================================================================

-- Receive verifications by store assignment (already exists - SKIP)
-- CREATE INDEX idx_receive_verifications_assignment ON receive_verifications(store_assignment_id) WHERE deleted_at IS NULL;

-- Receive verifications by verified user (already exists in psp_module_ddl.sql - SKIP)
-- CREATE INDEX idx_receive_verifications_user ON receive_verifications(verified_by_user_id) WHERE deleted_at IS NULL;

-- Receive verifications by shipment (already exists in psp_module_ddl.sql - SKIP)
-- CREATE INDEX idx_receive_verifications_shipment ON receive_verifications(shipment_id) WHERE deleted_at IS NULL;

-- Recent receive verifications
CREATE INDEX IF NOT EXISTS idx_receive_verifications_recent
  ON receive_verifications(verified_at DESC)
  WHERE deleted_at IS NULL;

COMMENT ON INDEX idx_receive_verifications_recent IS
  'Find most recent receive verifications across all assignments';

-- Receive verifications with damages (for quality tracking)
CREATE INDEX IF NOT EXISTS idx_receive_verifications_damages
  ON receive_verifications(verified_at DESC)
  WHERE received_damaged_qty > 0 AND deleted_at IS NULL;

COMMENT ON INDEX idx_receive_verifications_damages IS
  'Find receive verifications that reported damaged items';

-- Receive verifications with shortages (for quality tracking)
CREATE INDEX IF NOT EXISTS idx_receive_verifications_shortages
  ON receive_verifications(verified_at DESC)
  WHERE received_good_qty + received_damaged_qty < delivered_qty AND deleted_at IS NULL;

COMMENT ON INDEX idx_receive_verifications_shortages IS
  'Find receive verifications with quantity shortages';

-- Receive verifications metadata GIN index
CREATE INDEX IF NOT EXISTS idx_receive_verifications_metadata_gin
  ON receive_verifications USING GIN (verification_metadata)
  WHERE verification_metadata IS NOT NULL AND deleted_at IS NULL;

COMMENT ON INDEX idx_receive_verifications_metadata_gin IS
  'Query receive verifications by metadata (e.g., specific damage types or notes)';

-- =============================================================================
-- REORDERS QUERY INDEXES
-- =============================================================================

-- Reorders by issue request (already exists - SKIP)
-- CREATE INDEX idx_reorders_issue ON reorders(issue_request_id) WHERE deleted_at IS NULL;

-- Reorders by store order (already exists - SKIP)
-- CREATE INDEX idx_reorders_order ON reorders(store_order_id) WHERE deleted_at IS NULL;

-- Reorders by status (already exists in psp_module_ddl.sql - SKIP)
-- CREATE INDEX idx_reorders_status ON reorders(status) WHERE deleted_at IS NULL;

-- Pending reorders (partial index)
CREATE INDEX IF NOT EXISTS idx_reorders_pending
  ON reorders(created_at DESC)
  WHERE status = 'PENDING' AND deleted_at IS NULL;

COMMENT ON INDEX idx_reorders_pending IS
  'Find reorders awaiting processing';

-- Reorders by issue type (via join, but useful for direct queries)
CREATE INDEX IF NOT EXISTS idx_reorders_created_at
  ON reorders(created_at DESC)
  WHERE deleted_at IS NULL;

COMMENT ON INDEX idx_reorders_created_at IS
  'Find reorders by creation time for chronological tracking';

-- =============================================================================
-- CROSS-TABLE FULFILLMENT QUERY PATTERNS
-- =============================================================================

-- Pattern 1: Campaign Order Status Dashboard
-- Query: Find all orders for a campaign with their shipment status
-- Uses: idx_store_orders_campaign_status + idx_shipments_order

-- Pattern 2: Store Fulfillment Timeline
-- Query: Track all orders, shipments, and receipts for a store assignment
-- Uses: idx_store_orders_assignment + idx_shipments_order + idx_receive_verifications_assignment

-- Pattern 3: PSP Callback Processing
-- Query: Lookup order and update shipment status based on PSP reference
-- Uses: idx_store_orders_psp_ref + idx_shipments_order

-- Pattern 4: Shipment Exception Management
-- Query: Find all shipments with exceptions and their associated orders
-- Uses: idx_shipments_exceptions + idx_shipments_order (reverse join)

-- Pattern 5: Quality Monitoring
-- Query: Find orders with damages, shortages, or quantity variances
-- Uses: idx_receive_verifications_damages + idx_receive_verifications_shortages + idx_order_lines_qty_variance

-- =============================================================================
-- PERFORMANCE NOTES
-- =============================================================================

-- 1. PSP integration indexes prioritize nullable columns (psp_order_ref can be NULL initially)
-- 2. Status-based partial indexes reduce index size for transient statuses
-- 3. Timestamp indexes use DESC for recent-first queries (most common pattern)
-- 4. GIN indexes on JSONB arrays (tracking_numbers) enable element-level searches
-- 5. Quality monitoring indexes use computed conditions in WHERE clause
-- 6. Composite indexes ordered by: foreign key → status → timestamp
