-- ==============================================================================
-- FOREIGN KEY RELATIONSHIPS - Fulfillment
-- ==============================================================================
-- Module: Fulfillment
-- Tables: store_orders, order_lines, shipments, shipment_lines
-- Version: 1.0
-- Created: 2025-12-19
-- ==============================================================================

-- ==============================================================================
-- STORE ORDERS
-- ==============================================================================

-- Store order belongs to campaign
ALTER TABLE store_orders
  ADD CONSTRAINT fk_store_orders_campaign
  FOREIGN KEY (campaign_id)
  REFERENCES campaigns(id)
  ON DELETE RESTRICT  -- Cannot delete campaign with orders
  ON UPDATE CASCADE;

COMMENT ON CONSTRAINT fk_store_orders_campaign ON store_orders IS
  'Store order belongs to campaign; cannot delete campaign with active orders';

-- Store order belongs to store
ALTER TABLE store_orders
  ADD CONSTRAINT fk_store_orders_store
  FOREIGN KEY (store_id)
  REFERENCES stores(id)
  ON DELETE RESTRICT  -- Cannot delete store with orders
  ON UPDATE CASCADE;

COMMENT ON CONSTRAINT fk_store_orders_store ON store_orders IS
  'Store order belongs to store; cannot delete store with active orders';

-- Store order belongs to store assignment
ALTER TABLE store_orders
  ADD CONSTRAINT fk_store_orders_assignment
  FOREIGN KEY (store_assignment_id)
  REFERENCES store_assignments(id)
  ON DELETE RESTRICT  -- Cannot delete assignment with orders
  ON UPDATE CASCADE;

COMMENT ON CONSTRAINT fk_store_orders_assignment ON store_orders IS
  'Store order belongs to store assignment; cannot delete assignment with active orders';

-- Store order audit - generated by
ALTER TABLE store_orders
  ADD CONSTRAINT fk_store_orders_generated_by
  FOREIGN KEY (generated_by_user_id)
  REFERENCES users(id)
  ON DELETE SET NULL  -- Preserve order even if generator deleted
  ON UPDATE CASCADE;

COMMENT ON CONSTRAINT fk_store_orders_generated_by ON store_orders IS
  'User who generated this order; set to NULL if user deleted';

-- Store order audit - cancelled by
ALTER TABLE store_orders
  ADD CONSTRAINT fk_store_orders_cancelled_by
  FOREIGN KEY (cancelled_by_user_id)
  REFERENCES users(id)
  ON DELETE SET NULL  -- Preserve order even if canceller deleted
  ON UPDATE CASCADE;

COMMENT ON CONSTRAINT fk_store_orders_cancelled_by ON store_orders IS
  'User who cancelled this order; set to NULL if user deleted';

-- Store order audit - closed by
ALTER TABLE store_orders
  ADD CONSTRAINT fk_store_orders_closed_by
  FOREIGN KEY (closed_by_user_id)
  REFERENCES users(id)
  ON DELETE SET NULL  -- Preserve order even if closer deleted
  ON UPDATE CASCADE;

COMMENT ON CONSTRAINT fk_store_orders_closed_by ON store_orders IS
  'User who closed this order; set to NULL if user deleted';


-- ==============================================================================
-- ORDER LINES
-- ==============================================================================

-- Order line belongs to store order
ALTER TABLE order_lines
  ADD CONSTRAINT fk_order_lines_order
  FOREIGN KEY (store_order_id)
  REFERENCES store_orders(id)
  ON DELETE CASCADE  -- Delete lines when order deleted
  ON UPDATE CASCADE;

COMMENT ON CONSTRAINT fk_order_lines_order ON order_lines IS
  'Order line belongs to store order; cascade delete when order deleted';

-- Order line references kit item
ALTER TABLE order_lines
  ADD CONSTRAINT fk_order_lines_kit_item
  FOREIGN KEY (kit_item_id)
  REFERENCES kit_items(id)
  ON DELETE RESTRICT  -- Cannot delete kit item with order lines
  ON UPDATE CASCADE;

COMMENT ON CONSTRAINT fk_order_lines_kit_item ON order_lines IS
  'Order line references kit item; cannot delete kit item with active order lines';


-- ==============================================================================
-- SHIPMENTS
-- ==============================================================================

-- Shipment belongs to store order
ALTER TABLE shipments
  ADD CONSTRAINT fk_shipments_order
  FOREIGN KEY (store_order_id)
  REFERENCES store_orders(id)
  ON DELETE CASCADE  -- Delete shipments when order deleted
  ON UPDATE CASCADE;

COMMENT ON CONSTRAINT fk_shipments_order ON shipments IS
  'Shipment belongs to store order; cascade delete when order deleted';


-- ==============================================================================
-- SHIPMENT LINES
-- ==============================================================================

-- Shipment line belongs to shipment
ALTER TABLE shipment_lines
  ADD CONSTRAINT fk_shipment_lines_shipment
  FOREIGN KEY (shipment_id)
  REFERENCES shipments(id)
  ON DELETE CASCADE  -- Delete lines when shipment deleted
  ON UPDATE CASCADE;

COMMENT ON CONSTRAINT fk_shipment_lines_shipment ON shipment_lines IS
  'Shipment line belongs to shipment; cascade delete when shipment deleted';

-- Shipment line references kit item
ALTER TABLE shipment_lines
  ADD CONSTRAINT fk_shipment_lines_kit_item
  FOREIGN KEY (kit_item_id)
  REFERENCES kit_items(id)
  ON DELETE RESTRICT  -- Cannot delete kit item with shipment lines
  ON UPDATE CASCADE;

COMMENT ON CONSTRAINT fk_shipment_lines_kit_item ON shipment_lines IS
  'Shipment line references kit item; cannot delete kit item with active shipment lines';


-- ==============================================================================
-- END OF FULFILLMENT FOREIGN KEYS
-- ==============================================================================
